### ISSUE TITLE
npm ERR! sonos-web@1.0.0 start: `gulp bundle && node server.js`

### ISSUE THREAD

**Issue by max1404** [denysvitali/sonos-web#11] opened 2016-08-29 14:27 UTC
Hi, I have tried to install "sonos-web" on my Debian Jessie Server  - unfortunately without success.

```
cat /etc/debian_version
8.5
```

```
dpkg -l | grep -i nodejs
ii  node-underscore                       1.7.0~dfsg-1                         all          JavaScript's functional programming helper library - NodeJS
ii  nodejs                                0.10.29~dfsg-2                       amd64        evented I/O for V8 javascript
ii  nodejs-dev                            0.10.29~dfsg-2                       amd64        evented I/O for V8 javascript (development files)
```

```
git clone https://github.com/denysvitali/sonos-web
cd sonos-web/
npm install
npm install -g gulp
npm start
```

```
> sonos-web@1.0.0 start /var/www/sonos-web
> gulp bundle && node server.js


npm ERR! sonos-web@1.0.0 start: `gulp bundle && node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sonos-web@1.0.0 start script.
npm ERR! This is most likely a problem with the sonos-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp bundle && node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sonos-web
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /var/www/sonos-web
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/sonos-web/npm-debug.log
npm ERR! not ok code 0
```

**Comment by denysvitali** [comment] 2016-08-29 14:34
As stated by npm:
```
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```
Please do note I do use "node", see [here](https://github.com/denysvitali/sonos-web/blob/master/package.json#L31)

You may try to do a `sudo ln -s /usr/bin/nodejs /usr/bin/node` and see if it works

**Comment by max1404** [comment] 2016-08-30 06:08
Hi Denys ,

i'll continue, but it is not a good solution and there are other errors.

## Why it is not a good solution? 
If "node" is installed.
```
which node
/usr/sbin/node
apt-file search /usr/sbin/node
node: /usr/sbin/node
```

```
which nodejs
/usr/bin/nodejs
apt-file search /usr/bin/nodejs
nodejs: /usr/bin/nodejs
```

### Workaround
```
apt remove node
apt purge node
ln -s /usr/bin/nodejs /usr/bin/node
```

## Next Error "browserify"
```
Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/sonos-web/gulpfile.js:7:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

### Workaround
`npm install browserify`

## Next Error "gulp-util"
```
Error: Cannot find module 'gulp-util'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/sonos-web/gulpfile.js:13:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

### Workaround
`npm install gulp-util`

## Next Error "const in strict mode"
```
/var/www/sonos-web/server.js:2
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

### Help please
I have no idea. Ask for help.

**Comment by denysvitali** [comment] 2016-09-04 13:59
Dear max1404,
sorry for the late answer, I was quite busy last week.

Apparently some of your workarounds weren't correct.

## Node Error

First of all, apparently you had 2 node.js installed, am I right?
The version of node I personally use is 6.5.0, therefore you may need to install it via their custom repo, instead of the default that comes with Ubuntu/Debian repos.

To do so, remove node (`apt-get remove --purge nodejs`) and run the following to install the latest one:

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
``` 

## Error "browserify":

Apparently you didn't "npm install" correctly, because "browserify" is required by watchify (see `npm ls browserify` output to see the tree), try to npm install again.

## Error gulp-util
Same as before, gulp-util is required by gulp, which is required in my package.json file. Seems to me like an error while `npm install`ing. If you already `npm install`ed in the error above don't do it again, this error should be already gone.

## const in strict mode
This seems to me an error in babelify (ES6 transpiler), again, I think this is due to your node version / the fact that you didn't `npm install`ed correctly

## Unexpected token )
Older versions of node (prior to 6.0 IIRC) don't support ES6, therefore you may need to install Node v6+ to make it work. Again, this should already be solved if you solved the node error in the first step.


# Procedure
Before doing any other workaround, start with a clean install (remove node, remove npm, remove the cloned git folder) and repeat the steps again

First of all, install Node v6 by issuing the command from the "Node error" section above,
then `git clone https://github.com/denysvitali/sonos-web`, `cd sonos-web` and `npm install` from there.

Please do note that in a few seconds I'll push a change in order to allow everyone to install all the youtube, soundcloud, audioproxy, party plugins dependencies directly via npm install, therefore you may need to wait a couple of seconds after seeing this. Otherwise you'll have to issue the following command to install the plugin dependencies: `npm install plugins/{youtube,soundcloud,audioproxy,party}/`.

If you get any other error just write here, I'll be happy to solve your issues :+1:

**Comment by max1404** [comment] 2016-09-06 09:48
Thanks @denysvitali, it works now.

```
apt-get remove --purge nodejs
apt-get autoremove

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get install nodejs

cd /var/www
git clone https://github.com/denysvitali/sonos-web
cd sonos-web/

npm install
npm install -g gulp
npm start
```

**Comment by denysvitali** [comment] 2017-07-26 21:00
I'm closing this, since the issue is solved. If there is any other related problem, feel free to reopen / comment this issue

**Closed by denysvitali** 2017-07-26 21:00 UTC
Labels: Installation problems
