### ISSUE TITLE
Unable to play 'Artist - Song Title' - cannot connect to undefined:8888

### ISSUE THREAD

**Issue by ethicalhack3r** [denysvitali/sonos-web#18] opened 2016-10-30 20:53 UTC
Got the `SyntaxError: Unexpected token [` error after running `npm start`

Full error:

```
/private/tmp/sonos-web/server.js:213
    thePlayer.getState().then(([status, track, volume, isMuted, zone]) => {
                               ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

My full terminal session while installing: https://gist.github.com/ethicalhack3r/fc8341bff903500ddf5947ab53f64c4e

**Comment by denysvitali** [comment] 2016-10-30 21:04
You're running an outdated version of Node.js, please update to v7.0.0 or v6.9.1 LTS

**Comment by ethicalhack3r** [comment] 2016-10-30 21:30
After upgrading node and installing the ```request``` package I am able to run the application. Thank you! :)

I tried playing a YouTube video but the search results don't seem to be clickable for some reason. Tried in Firefox (49.0.2 latest) and Chrome (54.0.2840.71 latest).

**Comment by denysvitali** [comment] 2016-10-30 21:39
Can you take a look at the Developer Console to see if there is any error?
CTRL + SHIFT + K on Chrome (CMD + SHIFT + K) or CTRL + SHIF + J (CMD + SHIFT + J) on Chrome

**Comment by ethicalhack3r** [comment] 2016-10-30 21:43
A couple of things in the console but they don't think they are related:

Screenshot: http://imgur.com/a/WAKg9

**Comment by denysvitali** [comment] 2016-10-30 21:46
When you click a video, it gets added to the Sonos Queue. Could you please check with the Sonos app if the video appeared or can you press "play" on the Web interface?

**Comment by ethicalhack3r** [comment] 2016-10-30 22:20
Ah! Yes, it shows in my Sonos's app queue.

When I press play on the web interface, BBC Radio 2 plays (which is what I had playing on Sonos previously). I tried clearing the Sonos queue first, then clicking and pressing play, but had the same behaviour.

Installed ffmpeg with ```brew install ffmpeg```, restarted node and still the same issue.

So items are being added to the queue, but not playing.

Thanks for your help so far! Appreciate it! :)

**Comment by ethicalhack3r** [comment] 2016-10-30 22:26
OK, so I played a song to remove the radio (so the queue would play).

This is the error I'm getting after pressing play in the web interface: http://imgur.com/a/h98FQ

**Comment by denysvitali** [comment] 2016-11-18 19:45
Sorry for the (very) late reply:
the problem seems caused by this line: https://github.com/denysvitali/sonos-web/blob/master/plugins/youtube/main.js#L122

Can you please post the whole output of npm start from

**Comment by denysvitali** [comment] 2016-12-21 18:21
In branch `dev` I've fixed this bug.
Can you please do git clone -b dev `https://github.com/denysvitali/sonos-web` and then follow the install instructions again?

**Comment by denysvitali** [comment] 2017-07-26 20:59
I'm closing this issue since there was no answer. If you still encounter the problem, feel free to comment / reopen the issue :)

**Closed by denysvitali** 2017-07-26 20:59 UTC
Labels: bug

**Comment by Nicolazinho** [comment] 2018-07-06 02:02
@denysvitali I have the same issue. Updating to the `dev` version, resulted in the Sonos app telling me `the connection to http://{my-server-ip}:8888 was lost`

The npm logs say `[ffmpeg] Error while converting video: Cannot find ffmpeg`

**Comment by denysvitali** [comment] 2018-07-06 06:31
@Nicolazinho That error indicates that you don't have the ffmpeg binaries on your system. What OS are you using?  
If it's Unix based, you can confirm you have ffmpeg installed with `which ffmpeg`.

**Comment by Nicolazinho** [comment] 2018-07-07 01:59
@denysvitali my apologies for not reading the instructions closely. I installed `ffmpeg` and it works now! Thank you for your work.
