### ISSUE TITLE
Unable to install on Kubuntu/yakkety system

### ISSUE THREAD

**Issue by pippo73** [denysvitali/sonos-web#19] opened 2016-11-25 09:58 UTC
Hi all, 
I would like to test your system on my pc but I'm having some problems with it.

Could you help me pleas

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.10
Release:        16.10
Codename:       yakkety

```

```
# dpkg -l | grep -i nodejs
ii  node-underscore                                 1.7.0~dfsg-1ubuntu1                           all          JavaScript's functional programming helper library - NodeJS
ii  nodejs                                          4.2.6~dfsg-1ubuntu5                           amd64        evented I/O for V8 javascript
ii  nodejs-dev                                      4.2.6~dfsg-1ubuntu5                           amd64        evented I/O for V8 javascript (development files)
ii  nodejs-legacy                                   4.2.6~dfsg-1ubuntu5                           all          evented I/O for V8 javascript (legacy symlink)
```

```
# npm install
npm WARN lifecycle sonos-web@1.0.1~postinstall: cannot run in wd %s %s (wd=%s) sonos-web@1.0.1 npm-recursive-install --skip-root /tmp/S/sonos-web
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
```

May I post something more to help me troubleshoot it?

TNX

**Comment by denysvitali** [comment] 2016-11-25 10:10
Dear pippo73,
the problem may be caused by the Ubuntu Package Manager's node version.

In order to install the Node 6.x version you can use these commands:
ˋcurl -sL https://deb.nodesource.com/setup_6.x -o nodesource_setup.sh; sudo bash nodesource_setup.sh; sudo apt-get update && sudo apt-get install nodejs build-essential; rm nodesource_setup.sh´

After this, you may need to do an npm install from the sonos-web source folder, and then try again.

Let me know if this helps!

**Comment by pippo73** [comment] 2016-12-25 10:08
Hi, 
sorry for the late reply

I understood that the problem was node.js version related.

I hate to messup with the repo, so I've found a way to updatate it in a "ubuntu way"

`curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add && `

add the following lines to the **/etc/apt/sources.list.d/nodesource.list** file
```
deb https://deb.nodesource.com/node_6.x   yakkety   main
deb-src https://deb.nodesource.com/node_6.x   yakkety  main
```
and updated the repository.
Now I have node.js to the last version

```
$ nodejs -v
v6.9.2
```

But if I try to install your app, it gives me the followin error:

```
$ npm install

> sonos-web@1.0.1 postinstall /tmp/sonos-web
> npm-recursive-install --skip-root

Skipping root package.json...
Installing /tmp/sonos-web/plugins/audioproxy/package.json...
npm WARN sonos-web-audioproxy@1.0.0 No repository field.
npm WARN sonos-web-audioproxy@1.0.0 No license field.

Installing /tmp/sonos-web/plugins/party/package.json...
npm WARN sonos-web-party@1.0.0 No repository field.
npm WARN sonos-web-party@1.0.0 No license field.

Installing /tmp/sonos-web/plugins/soundcloud/package.json...
npm WARN sonos-web-soundcloud@1.0.0 No repository field.
npm WARN sonos-web-soundcloud@1.0.0 No license field.

Installing /tmp/sonos-web/plugins/youtube/package.json...
npm WARN sonos-web-youtube@1.0.0 No repository field.
npm WARN sonos-web-youtube@1.0.0 No license field.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

```

Hope it helps to troubleshoot it  :)

**Comment by denysvitali** [comment] 2016-12-25 10:26
I don't see any problem: those are only warnings. You can `npm run` now, you should be good to go!

Merry Christmas 🎄

**Comment by denysvitali** [comment] 2017-04-21 21:36
I'm closing this issue since it the one showed are only warnings. Feel free to comment if you're having problems.

**Closed by denysvitali** 2017-04-21 21:36 UTC
Labels: Installation problems
